ALTER TABLE public.grocery_items
  ADD COLUMN IF NOT EXISTS stock_quantity INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS expiry_date DATE,
  ADD COLUMN IF NOT EXISTS aisle_location TEXT;

ALTER TABLE public.menu_items
  ADD COLUMN IF NOT EXISTS prep_time_minutes INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS is_special BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS modifiers JSONB NOT NULL DEFAULT '[]'::jsonb;
