/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterPartnerRouteImport } from './routes/register-partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRiderIndexRouteImport } from './routes/_protected/rider/index'
import { Route as ProtectedHotelIndexRouteImport } from './routes/_protected/hotel/index'
import { Route as ProtectedGroceryAdminIndexRouteImport } from './routes/_protected/grocery-admin/index'
import { Route as ProtectedDeliveryIndexRouteImport } from './routes/_protected/delivery/index'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/app/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedRiderActiveRouteImport } from './routes/_protected/rider/active'
import { Route as ProtectedHotelOrdersRouteImport } from './routes/_protected/hotel/orders'
import { Route as ProtectedHotelMenuRouteImport } from './routes/_protected/hotel/menu'
import { Route as ProtectedGroceryAdminOrdersRouteImport } from './routes/_protected/grocery-admin/orders'
import { Route as ProtectedGroceryAdminItemsRouteImport } from './routes/_protected/grocery-admin/items'
import { Route as ProtectedDeliveryActiveRouteImport } from './routes/_protected/delivery/active'
import { Route as ProtectedAppTrackRouteImport } from './routes/_protected/app/track'
import { Route as ProtectedAppSupportRouteImport } from './routes/_protected/app/support'
import { Route as ProtectedAppRideRouteImport } from './routes/_protected/app/ride'
import { Route as ProtectedAppProfileRouteImport } from './routes/_protected/app/profile'
import { Route as ProtectedAppPackageRouteImport } from './routes/_protected/app/package'
import { Route as ProtectedAppOrdersRouteImport } from './routes/_protected/app/orders'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminRestaurantsRouteImport } from './routes/_protected/admin/restaurants'
import { Route as ProtectedAdminGroceryStoresRouteImport } from './routes/_protected/admin/grocery-stores'
import { Route as ProtectedAppGroceryIndexRouteImport } from './routes/_protected/app/grocery/index'
import { Route as ProtectedAppFoodIndexRouteImport } from './routes/_protected/app/food/index'
import { Route as ProtectedAppGroceryCheckoutRouteImport } from './routes/_protected/app/grocery/checkout'
import { Route as ProtectedAppGroceryStoreIdRouteImport } from './routes/_protected/app/grocery/$storeId'
import { Route as ProtectedAppFoodCheckoutRouteImport } from './routes/_protected/app/food/checkout'
import { Route as ProtectedAppFoodRestaurantIdRouteImport } from './routes/_protected/app/food/$restaurantId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPartnerRoute = RegisterPartnerRouteImport.update({
  id: '/register-partner',
  path: '/register-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRiderIndexRoute = ProtectedRiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHotelIndexRoute = ProtectedHotelIndexRouteImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGroceryAdminIndexRoute =
  ProtectedGroceryAdminIndexRouteImport.update({
    id: '/grocery-admin/',
    path: '/grocery-admin/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDeliveryIndexRoute = ProtectedDeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRiderActiveRoute = ProtectedRiderActiveRouteImport.update({
  id: '/rider/active',
  path: '/rider/active',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHotelOrdersRoute = ProtectedHotelOrdersRouteImport.update({
  id: '/hotel/orders',
  path: '/hotel/orders',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHotelMenuRoute = ProtectedHotelMenuRouteImport.update({
  id: '/hotel/menu',
  path: '/hotel/menu',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGroceryAdminOrdersRoute =
  ProtectedGroceryAdminOrdersRouteImport.update({
    id: '/grocery-admin/orders',
    path: '/grocery-admin/orders',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGroceryAdminItemsRoute =
  ProtectedGroceryAdminItemsRouteImport.update({
    id: '/grocery-admin/items',
    path: '/grocery-admin/items',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDeliveryActiveRoute = ProtectedDeliveryActiveRouteImport.update({
  id: '/delivery/active',
  path: '/delivery/active',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppTrackRoute = ProtectedAppTrackRouteImport.update({
  id: '/app/track',
  path: '/app/track',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppSupportRoute = ProtectedAppSupportRouteImport.update({
  id: '/app/support',
  path: '/app/support',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppRideRoute = ProtectedAppRideRouteImport.update({
  id: '/app/ride',
  path: '/app/ride',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppProfileRoute = ProtectedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppPackageRoute = ProtectedAppPackageRouteImport.update({
  id: '/app/package',
  path: '/app/package',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppOrdersRoute = ProtectedAppOrdersRouteImport.update({
  id: '/app/orders',
  path: '/app/orders',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRestaurantsRoute =
  ProtectedAdminRestaurantsRouteImport.update({
    id: '/admin/restaurants',
    path: '/admin/restaurants',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminGroceryStoresRoute =
  ProtectedAdminGroceryStoresRouteImport.update({
    id: '/admin/grocery-stores',
    path: '/admin/grocery-stores',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppGroceryIndexRoute =
  ProtectedAppGroceryIndexRouteImport.update({
    id: '/app/grocery/',
    path: '/app/grocery/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppFoodIndexRoute = ProtectedAppFoodIndexRouteImport.update({
  id: '/app/food/',
  path: '/app/food/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppGroceryCheckoutRoute =
  ProtectedAppGroceryCheckoutRouteImport.update({
    id: '/app/grocery/checkout',
    path: '/app/grocery/checkout',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppGroceryStoreIdRoute =
  ProtectedAppGroceryStoreIdRouteImport.update({
    id: '/app/grocery/$storeId',
    path: '/app/grocery/$storeId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppFoodCheckoutRoute =
  ProtectedAppFoodCheckoutRouteImport.update({
    id: '/app/food/checkout',
    path: '/app/food/checkout',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppFoodRestaurantIdRoute =
  ProtectedAppFoodRestaurantIdRouteImport.update({
    id: '/app/food/$restaurantId',
    path: '/app/food/$restaurantId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-partner': typeof RegisterPartnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/grocery-stores': typeof ProtectedAdminGroceryStoresRoute
  '/admin/restaurants': typeof ProtectedAdminRestaurantsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/app/orders': typeof ProtectedAppOrdersRoute
  '/app/package': typeof ProtectedAppPackageRoute
  '/app/profile': typeof ProtectedAppProfileRoute
  '/app/ride': typeof ProtectedAppRideRoute
  '/app/support': typeof ProtectedAppSupportRoute
  '/app/track': typeof ProtectedAppTrackRoute
  '/delivery/active': typeof ProtectedDeliveryActiveRoute
  '/grocery-admin/items': typeof ProtectedGroceryAdminItemsRoute
  '/grocery-admin/orders': typeof ProtectedGroceryAdminOrdersRoute
  '/hotel/menu': typeof ProtectedHotelMenuRoute
  '/hotel/orders': typeof ProtectedHotelOrdersRoute
  '/rider/active': typeof ProtectedRiderActiveRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/app/': typeof ProtectedAppIndexRoute
  '/delivery/': typeof ProtectedDeliveryIndexRoute
  '/grocery-admin/': typeof ProtectedGroceryAdminIndexRoute
  '/hotel/': typeof ProtectedHotelIndexRoute
  '/rider/': typeof ProtectedRiderIndexRoute
  '/app/food/$restaurantId': typeof ProtectedAppFoodRestaurantIdRoute
  '/app/food/checkout': typeof ProtectedAppFoodCheckoutRoute
  '/app/grocery/$storeId': typeof ProtectedAppGroceryStoreIdRoute
  '/app/grocery/checkout': typeof ProtectedAppGroceryCheckoutRoute
  '/app/food/': typeof ProtectedAppFoodIndexRoute
  '/app/grocery/': typeof ProtectedAppGroceryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-partner': typeof RegisterPartnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/grocery-stores': typeof ProtectedAdminGroceryStoresRoute
  '/admin/restaurants': typeof ProtectedAdminRestaurantsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/app/orders': typeof ProtectedAppOrdersRoute
  '/app/package': typeof ProtectedAppPackageRoute
  '/app/profile': typeof ProtectedAppProfileRoute
  '/app/ride': typeof ProtectedAppRideRoute
  '/app/support': typeof ProtectedAppSupportRoute
  '/app/track': typeof ProtectedAppTrackRoute
  '/delivery/active': typeof ProtectedDeliveryActiveRoute
  '/grocery-admin/items': typeof ProtectedGroceryAdminItemsRoute
  '/grocery-admin/orders': typeof ProtectedGroceryAdminOrdersRoute
  '/hotel/menu': typeof ProtectedHotelMenuRoute
  '/hotel/orders': typeof ProtectedHotelOrdersRoute
  '/rider/active': typeof ProtectedRiderActiveRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/app': typeof ProtectedAppIndexRoute
  '/delivery': typeof ProtectedDeliveryIndexRoute
  '/grocery-admin': typeof ProtectedGroceryAdminIndexRoute
  '/hotel': typeof ProtectedHotelIndexRoute
  '/rider': typeof ProtectedRiderIndexRoute
  '/app/food/$restaurantId': typeof ProtectedAppFoodRestaurantIdRoute
  '/app/food/checkout': typeof ProtectedAppFoodCheckoutRoute
  '/app/grocery/$storeId': typeof ProtectedAppGroceryStoreIdRoute
  '/app/grocery/checkout': typeof ProtectedAppGroceryCheckoutRoute
  '/app/food': typeof ProtectedAppFoodIndexRoute
  '/app/grocery': typeof ProtectedAppGroceryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-partner': typeof RegisterPartnerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/admin/grocery-stores': typeof ProtectedAdminGroceryStoresRoute
  '/_protected/admin/restaurants': typeof ProtectedAdminRestaurantsRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/app/orders': typeof ProtectedAppOrdersRoute
  '/_protected/app/package': typeof ProtectedAppPackageRoute
  '/_protected/app/profile': typeof ProtectedAppProfileRoute
  '/_protected/app/ride': typeof ProtectedAppRideRoute
  '/_protected/app/support': typeof ProtectedAppSupportRoute
  '/_protected/app/track': typeof ProtectedAppTrackRoute
  '/_protected/delivery/active': typeof ProtectedDeliveryActiveRoute
  '/_protected/grocery-admin/items': typeof ProtectedGroceryAdminItemsRoute
  '/_protected/grocery-admin/orders': typeof ProtectedGroceryAdminOrdersRoute
  '/_protected/hotel/menu': typeof ProtectedHotelMenuRoute
  '/_protected/hotel/orders': typeof ProtectedHotelOrdersRoute
  '/_protected/rider/active': typeof ProtectedRiderActiveRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/app/': typeof ProtectedAppIndexRoute
  '/_protected/delivery/': typeof ProtectedDeliveryIndexRoute
  '/_protected/grocery-admin/': typeof ProtectedGroceryAdminIndexRoute
  '/_protected/hotel/': typeof ProtectedHotelIndexRoute
  '/_protected/rider/': typeof ProtectedRiderIndexRoute
  '/_protected/app/food/$restaurantId': typeof ProtectedAppFoodRestaurantIdRoute
  '/_protected/app/food/checkout': typeof ProtectedAppFoodCheckoutRoute
  '/_protected/app/grocery/$storeId': typeof ProtectedAppGroceryStoreIdRoute
  '/_protected/app/grocery/checkout': typeof ProtectedAppGroceryCheckoutRoute
  '/_protected/app/food/': typeof ProtectedAppFoodIndexRoute
  '/_protected/app/grocery/': typeof ProtectedAppGroceryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-partner'
    | '/reset-password'
    | '/admin/grocery-stores'
    | '/admin/restaurants'
    | '/admin/users'
    | '/app/orders'
    | '/app/package'
    | '/app/profile'
    | '/app/ride'
    | '/app/support'
    | '/app/track'
    | '/delivery/active'
    | '/grocery-admin/items'
    | '/grocery-admin/orders'
    | '/hotel/menu'
    | '/hotel/orders'
    | '/rider/active'
    | '/admin/'
    | '/app/'
    | '/delivery/'
    | '/grocery-admin/'
    | '/hotel/'
    | '/rider/'
    | '/app/food/$restaurantId'
    | '/app/food/checkout'
    | '/app/grocery/$storeId'
    | '/app/grocery/checkout'
    | '/app/food/'
    | '/app/grocery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-partner'
    | '/reset-password'
    | '/admin/grocery-stores'
    | '/admin/restaurants'
    | '/admin/users'
    | '/app/orders'
    | '/app/package'
    | '/app/profile'
    | '/app/ride'
    | '/app/support'
    | '/app/track'
    | '/delivery/active'
    | '/grocery-admin/items'
    | '/grocery-admin/orders'
    | '/hotel/menu'
    | '/hotel/orders'
    | '/rider/active'
    | '/admin'
    | '/app'
    | '/delivery'
    | '/grocery-admin'
    | '/hotel'
    | '/rider'
    | '/app/food/$restaurantId'
    | '/app/food/checkout'
    | '/app/grocery/$storeId'
    | '/app/grocery/checkout'
    | '/app/food'
    | '/app/grocery'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-partner'
    | '/reset-password'
    | '/_protected/admin/grocery-stores'
    | '/_protected/admin/restaurants'
    | '/_protected/admin/users'
    | '/_protected/app/orders'
    | '/_protected/app/package'
    | '/_protected/app/profile'
    | '/_protected/app/ride'
    | '/_protected/app/support'
    | '/_protected/app/track'
    | '/_protected/delivery/active'
    | '/_protected/grocery-admin/items'
    | '/_protected/grocery-admin/orders'
    | '/_protected/hotel/menu'
    | '/_protected/hotel/orders'
    | '/_protected/rider/active'
    | '/_protected/admin/'
    | '/_protected/app/'
    | '/_protected/delivery/'
    | '/_protected/grocery-admin/'
    | '/_protected/hotel/'
    | '/_protected/rider/'
    | '/_protected/app/food/$restaurantId'
    | '/_protected/app/food/checkout'
    | '/_protected/app/grocery/$storeId'
    | '/_protected/app/grocery/checkout'
    | '/_protected/app/food/'
    | '/_protected/app/grocery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterPartnerRoute: typeof RegisterPartnerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-partner': {
      id: '/register-partner'
      path: '/register-partner'
      fullPath: '/register-partner'
      preLoaderRoute: typeof RegisterPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/rider/': {
      id: '/_protected/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof ProtectedRiderIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hotel/': {
      id: '/_protected/hotel/'
      path: '/hotel'
      fullPath: '/hotel/'
      preLoaderRoute: typeof ProtectedHotelIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/grocery-admin/': {
      id: '/_protected/grocery-admin/'
      path: '/grocery-admin'
      fullPath: '/grocery-admin/'
      preLoaderRoute: typeof ProtectedGroceryAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/delivery/': {
      id: '/_protected/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof ProtectedDeliveryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/rider/active': {
      id: '/_protected/rider/active'
      path: '/rider/active'
      fullPath: '/rider/active'
      preLoaderRoute: typeof ProtectedRiderActiveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hotel/orders': {
      id: '/_protected/hotel/orders'
      path: '/hotel/orders'
      fullPath: '/hotel/orders'
      preLoaderRoute: typeof ProtectedHotelOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hotel/menu': {
      id: '/_protected/hotel/menu'
      path: '/hotel/menu'
      fullPath: '/hotel/menu'
      preLoaderRoute: typeof ProtectedHotelMenuRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/grocery-admin/orders': {
      id: '/_protected/grocery-admin/orders'
      path: '/grocery-admin/orders'
      fullPath: '/grocery-admin/orders'
      preLoaderRoute: typeof ProtectedGroceryAdminOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/grocery-admin/items': {
      id: '/_protected/grocery-admin/items'
      path: '/grocery-admin/items'
      fullPath: '/grocery-admin/items'
      preLoaderRoute: typeof ProtectedGroceryAdminItemsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/delivery/active': {
      id: '/_protected/delivery/active'
      path: '/delivery/active'
      fullPath: '/delivery/active'
      preLoaderRoute: typeof ProtectedDeliveryActiveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/track': {
      id: '/_protected/app/track'
      path: '/app/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof ProtectedAppTrackRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/support': {
      id: '/_protected/app/support'
      path: '/app/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof ProtectedAppSupportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/ride': {
      id: '/_protected/app/ride'
      path: '/app/ride'
      fullPath: '/app/ride'
      preLoaderRoute: typeof ProtectedAppRideRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/profile': {
      id: '/_protected/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof ProtectedAppProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/package': {
      id: '/_protected/app/package'
      path: '/app/package'
      fullPath: '/app/package'
      preLoaderRoute: typeof ProtectedAppPackageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/orders': {
      id: '/_protected/app/orders'
      path: '/app/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof ProtectedAppOrdersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/restaurants': {
      id: '/_protected/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof ProtectedAdminRestaurantsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/grocery-stores': {
      id: '/_protected/admin/grocery-stores'
      path: '/admin/grocery-stores'
      fullPath: '/admin/grocery-stores'
      preLoaderRoute: typeof ProtectedAdminGroceryStoresRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/grocery/': {
      id: '/_protected/app/grocery/'
      path: '/app/grocery'
      fullPath: '/app/grocery/'
      preLoaderRoute: typeof ProtectedAppGroceryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/food/': {
      id: '/_protected/app/food/'
      path: '/app/food'
      fullPath: '/app/food/'
      preLoaderRoute: typeof ProtectedAppFoodIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/grocery/checkout': {
      id: '/_protected/app/grocery/checkout'
      path: '/app/grocery/checkout'
      fullPath: '/app/grocery/checkout'
      preLoaderRoute: typeof ProtectedAppGroceryCheckoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/grocery/$storeId': {
      id: '/_protected/app/grocery/$storeId'
      path: '/app/grocery/$storeId'
      fullPath: '/app/grocery/$storeId'
      preLoaderRoute: typeof ProtectedAppGroceryStoreIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/food/checkout': {
      id: '/_protected/app/food/checkout'
      path: '/app/food/checkout'
      fullPath: '/app/food/checkout'
      preLoaderRoute: typeof ProtectedAppFoodCheckoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app/food/$restaurantId': {
      id: '/_protected/app/food/$restaurantId'
      path: '/app/food/$restaurantId'
      fullPath: '/app/food/$restaurantId'
      preLoaderRoute: typeof ProtectedAppFoodRestaurantIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminGroceryStoresRoute: typeof ProtectedAdminGroceryStoresRoute
  ProtectedAdminRestaurantsRoute: typeof ProtectedAdminRestaurantsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAppOrdersRoute: typeof ProtectedAppOrdersRoute
  ProtectedAppPackageRoute: typeof ProtectedAppPackageRoute
  ProtectedAppProfileRoute: typeof ProtectedAppProfileRoute
  ProtectedAppRideRoute: typeof ProtectedAppRideRoute
  ProtectedAppSupportRoute: typeof ProtectedAppSupportRoute
  ProtectedAppTrackRoute: typeof ProtectedAppTrackRoute
  ProtectedDeliveryActiveRoute: typeof ProtectedDeliveryActiveRoute
  ProtectedGroceryAdminItemsRoute: typeof ProtectedGroceryAdminItemsRoute
  ProtectedGroceryAdminOrdersRoute: typeof ProtectedGroceryAdminOrdersRoute
  ProtectedHotelMenuRoute: typeof ProtectedHotelMenuRoute
  ProtectedHotelOrdersRoute: typeof ProtectedHotelOrdersRoute
  ProtectedRiderActiveRoute: typeof ProtectedRiderActiveRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedDeliveryIndexRoute: typeof ProtectedDeliveryIndexRoute
  ProtectedGroceryAdminIndexRoute: typeof ProtectedGroceryAdminIndexRoute
  ProtectedHotelIndexRoute: typeof ProtectedHotelIndexRoute
  ProtectedRiderIndexRoute: typeof ProtectedRiderIndexRoute
  ProtectedAppFoodRestaurantIdRoute: typeof ProtectedAppFoodRestaurantIdRoute
  ProtectedAppFoodCheckoutRoute: typeof ProtectedAppFoodCheckoutRoute
  ProtectedAppGroceryStoreIdRoute: typeof ProtectedAppGroceryStoreIdRoute
  ProtectedAppGroceryCheckoutRoute: typeof ProtectedAppGroceryCheckoutRoute
  ProtectedAppFoodIndexRoute: typeof ProtectedAppFoodIndexRoute
  ProtectedAppGroceryIndexRoute: typeof ProtectedAppGroceryIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminGroceryStoresRoute: ProtectedAdminGroceryStoresRoute,
  ProtectedAdminRestaurantsRoute: ProtectedAdminRestaurantsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAppOrdersRoute: ProtectedAppOrdersRoute,
  ProtectedAppPackageRoute: ProtectedAppPackageRoute,
  ProtectedAppProfileRoute: ProtectedAppProfileRoute,
  ProtectedAppRideRoute: ProtectedAppRideRoute,
  ProtectedAppSupportRoute: ProtectedAppSupportRoute,
  ProtectedAppTrackRoute: ProtectedAppTrackRoute,
  ProtectedDeliveryActiveRoute: ProtectedDeliveryActiveRoute,
  ProtectedGroceryAdminItemsRoute: ProtectedGroceryAdminItemsRoute,
  ProtectedGroceryAdminOrdersRoute: ProtectedGroceryAdminOrdersRoute,
  ProtectedHotelMenuRoute: ProtectedHotelMenuRoute,
  ProtectedHotelOrdersRoute: ProtectedHotelOrdersRoute,
  ProtectedRiderActiveRoute: ProtectedRiderActiveRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedDeliveryIndexRoute: ProtectedDeliveryIndexRoute,
  ProtectedGroceryAdminIndexRoute: ProtectedGroceryAdminIndexRoute,
  ProtectedHotelIndexRoute: ProtectedHotelIndexRoute,
  ProtectedRiderIndexRoute: ProtectedRiderIndexRoute,
  ProtectedAppFoodRestaurantIdRoute: ProtectedAppFoodRestaurantIdRoute,
  ProtectedAppFoodCheckoutRoute: ProtectedAppFoodCheckoutRoute,
  ProtectedAppGroceryStoreIdRoute: ProtectedAppGroceryStoreIdRoute,
  ProtectedAppGroceryCheckoutRoute: ProtectedAppGroceryCheckoutRoute,
  ProtectedAppFoodIndexRoute: ProtectedAppFoodIndexRoute,
  ProtectedAppGroceryIndexRoute: ProtectedAppGroceryIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterPartnerRoute: RegisterPartnerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
